version: 1.0.{build}
image:
- macOS-BigSur
- Ubuntu
- Visual Studio 2019
environment:
  TOXENV: py38
  CIBW_ARCHS_MACOS: x86_64 universal2 arm64
  CIBW_ARCHS_LINUX: auto
  CIBW_PRERELEASE_PYTHONS: True
build_script:
- ps: >-
    if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019") {
        & py -3.10 -m pip install -U pip setuptools setuptools_scm[toml] tox build twine --user
        & py -3.10 -m tox 
    } else {
        & python3 -m ensurepip --user
        & python3 install -U pip setuptools setuptools_scm[toml] tox build twine --user
        & python3 -m tox
    }
    if ($env:APPVEYOR_REPO_TAG -eq "true" -and $env:APPVEYOR_REPO_TAG_NAME.StartsWith("v")) {
        $release = "pypi"
    } elseif ($env:APPVEYOR_REPO_BRANCH.StartsWith("releases/")) {
        $release = "testpypi"
    }
    if ($release -ne $null) {
        if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019") {
            & py -3.10 -m pip install cibuildwheel==2.8.0
            & py -3.10 -m cibuildwheel --output-dir wheelhouse .
            & py -3.10 -m twine upload --non-interactive -r pypi wheelhouse/*.whl
        } else {
            & python -m pip install cibuildwheel==2.8.0
            & python -m cibuildwheel --output-dir wheelhouse .
            if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Ubuntu") {
                  & python -m build --sdist
            }
            & python -m twine upload --non-interactive -r $(release) wheelhouse/*.whl dist/*
        }
    } else  {
        Write-Output "Skip build wheel"
    }
