name: Run Tox tests

on:
  push:
    branches:
      - main
      - releases/*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [
            "3.8",
            "3.10",
        ]
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          pip install -U pip tox wheel setuptools
          pip install tox-gh-actions coveralls coverage[toml] setuptools_scm[toml]
      - name: Test project with tox
        run: |
          tox
        env:
          PYTEST_ADDOPTS: "--cov-config=pyproject.toml --cov --cov-append"

